# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rock_paper_scissors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rock_paper_scissors.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19rock_paper_scissors.proto\"\x15\n\x05Gamer\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\tGamerList\x12\x0e\n\x06gamers\x18\x01 \x03(\t\":\n\tGameRound\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x1e\n\ngamer_list\x18\x02 \x01(\x0b\x32\n.GamerList\"/\n\nPlayerHand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x04hand\x18\x02 \x01(\x0e\x32\x05.Hand\"D\n\nGameResult\x12\x13\n\x0bwinner_name\x18\x01 \x01(\t\x12!\n\x0cplayer_hands\x18\x02 \x03(\x0b\x32\x0b.PlayerHand*3\n\x04Hand\x12\x08\n\x04WILD\x10\x00\x12\x08\n\x04ROCK\x10\x01\x12\t\n\x05PAPER\x10\x02\x12\x0c\n\x08SCISSORS\x10\x03\x32{\n\x11RockPaperScissors\x12\x1e\n\x08JoinGame\x12\x06.Gamer\x1a\n.GamerList\x12 \n\nStartRound\x12\x06.Gamer\x1a\n.GameRound\x12$\n\x08PlayHand\x12\x0b.PlayerHand\x1a\x0b.GameResultb\x06proto3'
)

_HAND = _descriptor.EnumDescriptor(
  name='Hand',
  full_name='Hand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WILD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROCK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAPER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCISSORS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=260,
  serialized_end=311,
)
_sym_db.RegisterEnumDescriptor(_HAND)

Hand = enum_type_wrapper.EnumTypeWrapper(_HAND)
WILD = 0
ROCK = 1
PAPER = 2
SCISSORS = 3



_GAMER = _descriptor.Descriptor(
  name='Gamer',
  full_name='Gamer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Gamer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=50,
)


_GAMERLIST = _descriptor.Descriptor(
  name='GamerList',
  full_name='GamerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gamers', full_name='GamerList.gamers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=79,
)


_GAMEROUND = _descriptor.Descriptor(
  name='GameRound',
  full_name='GameRound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='round', full_name='GameRound.round', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamer_list', full_name='GameRound.gamer_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=139,
)


_PLAYERHAND = _descriptor.Descriptor(
  name='PlayerHand',
  full_name='PlayerHand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PlayerHand.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hand', full_name='PlayerHand.hand', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=188,
)


_GAMERESULT = _descriptor.Descriptor(
  name='GameResult',
  full_name='GameResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='winner_name', full_name='GameResult.winner_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_hands', full_name='GameResult.player_hands', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=258,
)

_GAMEROUND.fields_by_name['gamer_list'].message_type = _GAMERLIST
_PLAYERHAND.fields_by_name['hand'].enum_type = _HAND
_GAMERESULT.fields_by_name['player_hands'].message_type = _PLAYERHAND
DESCRIPTOR.message_types_by_name['Gamer'] = _GAMER
DESCRIPTOR.message_types_by_name['GamerList'] = _GAMERLIST
DESCRIPTOR.message_types_by_name['GameRound'] = _GAMEROUND
DESCRIPTOR.message_types_by_name['PlayerHand'] = _PLAYERHAND
DESCRIPTOR.message_types_by_name['GameResult'] = _GAMERESULT
DESCRIPTOR.enum_types_by_name['Hand'] = _HAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gamer = _reflection.GeneratedProtocolMessageType('Gamer', (_message.Message,), {
  'DESCRIPTOR' : _GAMER,
  '__module__' : 'rock_paper_scissors_pb2'
  # @@protoc_insertion_point(class_scope:Gamer)
  })
_sym_db.RegisterMessage(Gamer)

GamerList = _reflection.GeneratedProtocolMessageType('GamerList', (_message.Message,), {
  'DESCRIPTOR' : _GAMERLIST,
  '__module__' : 'rock_paper_scissors_pb2'
  # @@protoc_insertion_point(class_scope:GamerList)
  })
_sym_db.RegisterMessage(GamerList)

GameRound = _reflection.GeneratedProtocolMessageType('GameRound', (_message.Message,), {
  'DESCRIPTOR' : _GAMEROUND,
  '__module__' : 'rock_paper_scissors_pb2'
  # @@protoc_insertion_point(class_scope:GameRound)
  })
_sym_db.RegisterMessage(GameRound)

PlayerHand = _reflection.GeneratedProtocolMessageType('PlayerHand', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERHAND,
  '__module__' : 'rock_paper_scissors_pb2'
  # @@protoc_insertion_point(class_scope:PlayerHand)
  })
_sym_db.RegisterMessage(PlayerHand)

GameResult = _reflection.GeneratedProtocolMessageType('GameResult', (_message.Message,), {
  'DESCRIPTOR' : _GAMERESULT,
  '__module__' : 'rock_paper_scissors_pb2'
  # @@protoc_insertion_point(class_scope:GameResult)
  })
_sym_db.RegisterMessage(GameResult)



_ROCKPAPERSCISSORS = _descriptor.ServiceDescriptor(
  name='RockPaperScissors',
  full_name='RockPaperScissors',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=313,
  serialized_end=436,
  methods=[
  _descriptor.MethodDescriptor(
    name='JoinGame',
    full_name='RockPaperScissors.JoinGame',
    index=0,
    containing_service=None,
    input_type=_GAMER,
    output_type=_GAMERLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartRound',
    full_name='RockPaperScissors.StartRound',
    index=1,
    containing_service=None,
    input_type=_GAMER,
    output_type=_GAMEROUND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PlayHand',
    full_name='RockPaperScissors.PlayHand',
    index=2,
    containing_service=None,
    input_type=_PLAYERHAND,
    output_type=_GAMERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROCKPAPERSCISSORS)

DESCRIPTOR.services_by_name['RockPaperScissors'] = _ROCKPAPERSCISSORS

# @@protoc_insertion_point(module_scope)
